[project]
name = "handson-llm"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.11.0",
    "ipywidgets>=8.1.7",
    "notebook>=7.4.7",
    "safetensors>=0.6.2",
    "transformers[torch]>=4.57.1",
]
